# Evaluate PII Extraction
dataset_args:
  dataset_path: ../src/pii_leakage/extern/echr
  dataset_mode: undefended
  sample_duplication_rate: 1

attack_args:
  attack_name: naive_extraction
  sampling_rate: 15000
  # sampling_rate: 2500
  seq_len: 256

model_args:
  architecture: gpt2
  pre_trained: True
  model_ckpt: ../pii_results/MG02

ner_args:
  ner: flair
  ner_model: flair/ner-english-ontonotes-large
  anon_token: <MASK>
  anonymize: False

env_args:
  # eval_batch_size: 64
  eval_batch_size: 8