# Fine-tune an LM on the enron text dataset.

# train size: 0.3 BERT Generation Decoder Model
dataset_args:
  dataset_path: ../src/pii_leakage/extern/echr
  dataset_mode: undefended
  sample_duplication_rate: 1

trainer_args:
  save_steps: 750
  callback_after_n_steps: 750
  num_train_epochs: 4
  gradient_accumulation_steps: 8
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2

model_args:
  architecture: google/bert_for_seq_generation_L-24_bbc_encoder
  pre_trained: True   # Start from a pre-trained checkpoint

ner_args:
  ner: flair
  ner_model: flair/ner-english-ontonotes-large
  anon_token: <MASK>
  anonymize: False
